definitions:
  models.Result:
    properties:
      code:
        example: 200
        type: integer
      data:
        type: object
      message:
        example: 请求信息
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: yang@mail.com
    name: Yang KUn
    url: http://localhost:8080
  description: Gin swagger Demo
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin swagger
  version: "1.0"
paths:
  /api/querybyid/{id}:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Result'
      summary: 通过 id 获取单条记录内容
  /api/queryvmbyname/{name}:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: name
        in: path
        name: name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Result'
      summary: 通过 id 获取虚拟机summary内容
swagger: "2.0"
